# -*- coding: utf-8 -*-
"""practica 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HL7h8IzAG2M6jijb3IBM0KoQuRyonWVm
"""

#Determinar e informar el mayor valor de 3 numeros enteros. ¿Que cambiarıas en el algoritmo si se
#trataran de 3 numeros reales o de 3 caracteres o de 3 palabras?. ¿Y si se buscara el menor valor?

num1 = int(input("Ingrese primer numero: "))
num2 = int(input("Ingrese segundo numero: "))
num3 = int(input("Ingrese tercer numero: "))
mayor=num1
if num2 > mayor:
  mayor = num2
if num3 > mayor:
  mayor = num3

print("El mayor es: ", mayor)

def determine_triangulo(l1, l2, l3):
  if l1 == l2 and l1==l3:
    return "Es equilatero"
  elif l1 == l2 or l1 == l3 or l2==l3:
    return "Es isoceles"
  else:
    return "Es escaleno"

l1 = input("Ingrese lado 1: ")
l2 = input("Ingrese lado 2: ")
l3 = input("Ingrese lado 3: ")

x = determine_triangulo(l1, l2, l3)

print(x)

def calificacionNumerica (cali):
  if cali == 'I':
    return 5
  elif cali == 'A':
    return 6
  elif cali == 'B':
    return 7
  elif cali == 'M':
    return 8
  elif cali == 'D':
    return 9
  elif cali == 'E':
    return 10

lista = ['I', 'A', 'B', 'M', 'D', 'E']
cali = input("Ingrese la nota alfabética: ")
cali = cali.upper()
while not cali in lista:
  print("No ha ingresado una nota válida, ingrese nuevamente")
  cali = input("Ingrese la nota alfabética: ")
  cali = cali.upper()
calificacionNumerica(cali)

# Ejercicio 6 práctica 3


lista = ["1", "2", "3"]
fecha = input("Cual es su fecha de cumpleaños? (Ingrese la fecha con el formato DD/MM)")

if len(fecha) != 5 or fecha[2] != "/" or fecha[0] not in lista:
  print("Error ha ingresado mal el formato")
else:
  dia = int(fecha[0:2])
  mes = int(fecha[3:])
  if (mes == 1 and dia >= 20) or (mes == 2 and dia <= 18):
        signo = "Acuario"
  elif (mes == 2 and dia >= 19) or (mes == 3 and dia <= 20):
        signo = "Piscis"
  elif (mes == 3 and dia >= 21) or (mes == 4 and dia <= 19):
        signo = "Aries"
  elif (mes == 4 and dia >= 20) or (mes == 5 and dia <= 20):
        signo = "Tauro"
  elif (mes == 5 and dia >= 21) or (mes == 6 and dia <= 20):
        signo = "Géminis"
  elif (mes == 6 and dia >= 21) or (mes == 7 and dia <= 22):
        signo = "Cáncer"
  elif (mes == 7 and dia >= 23) or (mes == 8 and dia <= 22):
        signo = "Leo"
  elif (mes == 8 and dia >= 23) or (mes == 9 and dia <= 22):
        signo = "Virgo"
  elif (mes == 9 and dia >= 23) or (mes == 10 and dia <= 22):
        signo = "Libra"
  elif (mes == 10 and dia >= 23) or (mes == 11 and dia <= 21):
        signo = "Escorpio"
  elif (mes == 11 and dia >= 22) or (mes == 12 and dia <= 21):
        signo = "Sagitario"
  elif (mes == 12 and dia >= 22) or (mes == 1 and dia <= 19):
        signo = "Capricornio"
  print("Su signo zodiacal es", signo)

#Ejercicio 7 Práctica 3

zona = input("Ingrese la zona del estacionamiento, A, B o C: ")
zona = zona.upper()

if zona == "A" or zona == "B" or zona == "C":
  horas = int(input("Ingrese la cantidad de horas de estacionamiento (máximo 3): "))
  if horas < 3 and horas > 0:
    if zona == "A":
        if horas == 1:
          tarifa = 57.00
        elif horas == 2:
          tarifa = 71.20
        else:
          tarifa = 85.5
    if zona == "B":
        if horas == 1:
          tarifa = 47.00
        elif horas == 2:
          tarifa = 58.70
        else:
          tarifa = 70.50
    if zona == "C":
        if horas == 1:
          tarifa = 37.00
        elif horas == 2:
          tarifa = 46.20
        else:
          tarifa = 55.50
    print("El costo total de estacionamiento es: $", tarifa)
  elif horas > 3:
    print("El vehículo debe moverse después de 3 horas de estacionamiento.")
  else:
    print("El tiempo negativo no existe")
else:
  print("No ha ingresado una zona válida")

#Ejercicio 8 Prácica 3
lista_sedes = ['rosario', 'funes', 'roldan']
lista_items = ["zapatillas", "remeras", "pantalones"]
item = input("Ingrese un item,(Zapatillas, Remeras, Pantalones): ")
item = item.lower()
if item in lista_items:
  sede = input("Ingrese la sede donde los compro, (Rosario, Funes, Roldan): ")
  sede = sede.lower()
  if sede in lista_sedes:
    if item == "zapatillas":
      if sede == "rosario":
        descuento = "30 %"
      elif sede == "funes":
        descuento = "40 %"
      elif sede == "Roldan":
        descuento = "25 %"

    elif item == "remeras":
      if sede == "rosario":
        descuento = "20 %"
      elif sede == "funes":
        descuento = "30 %"
      elif sede == "roldan":
        descuento = "15 %"

    elif item == "pantalones":
      if sede == "rosario":
        descuento = "10 %"
      elif sede == "funes":
        descuento = "5 %"
      elif sede == "roldan":
        descuento = "20 %"
    print(descuento)
  else:
    print("No ha ingresado una sede válida")

else:
  print("No ha ingresado un item válido")

#Ejercicio 9 Práctica 3
lista_dias = ["lunes", "martes", "jueves"]
lista_sedes = ['rosario', 'funes', 'roldan']
lista_items = ["zapatillas", "remeras", "pantalones"]
item = input("Ingrese un item,(Zapatillas, Remeras, Pantalones): ")
item = item.lower()
if item in lista_items:
  sede = input("Ingrese la sede donde los compro, (Rosario, Funes, Roldan): ")
  sede = sede.lower()
  if sede in lista_sedes:
    if item == "zapatillas":
      if sede == "rosario":
        descuento = 30
      elif sede == "funes":
        descuento = 40
      elif sede == "Roldan":
        descuento = 25

    elif item == "remeras":
      if sede == "rosario":
        descuento = 20
      elif sede == "funes":
        descuento = 30
      elif sede == "roldan":
        descuento = 15

    elif item == "pantalones":
      if sede == "rosario":
        descuento = 10
      elif sede == "funes":
        descuento = 5
      elif sede == "roldan":
        descuento = 20

    dia = input("Ingrese dia de la semana en que lo compro: ")
    dia = dia.lower()
    if dia in lista_dias:
      if dia == "lunes":
        descuento = descuento + 10
      elif dia == "miercoles":
        descuento = descuento + 8
      elif dia == "jueves":
        descuento ==descuento + 5
      print(descuento, "%")
    else:
      print(descuento, "%")

  else:
    print("No ha ingresado una sede válida")

else:
  print("No ha ingresado un item válido")