# -*- coding: utf-8 -*-
"""Práctica 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SifKblTtVSKWbrpmYgPG-HHYlrwKfNVm
"""

# Ejercicio 1 Práctica 4
x = 1
while x < 21:
  print(x)
  x += 1

#Ejercicio 2

x = 0
while x < 11:
  print(5 * x)
  x += 1

#Ejercicio 3

x = -10
while x < 0:
  print(x)
  x += 1

#Ejercicio 4

numeros = [12 , 75 , 150 , 180 , 145 , 525 , 50]
for i in numeros:
  if not i%5 and i < 150:
    print(i)

#Ejercicio 5
x = 0
y = 1
print(x)
print(y)
for i in range(8):
  z = x + y
  print(z)
  x = y
  y = z

#Ejercicio 6
i = 1
x = 5
while i<5:
  x = x * i
  if i == 4:
    print(x)
  i += 1

#Ejercicio 7

lista = []
for j in lista :
  print ( j )

i = 1
for i in [1 , 2 , 3]:
  print ( i )
print(i)

#Ejercicio 8 a

for i in range(1, 11):
  x = i*i
  print(x)

#Ejercicio 8 b
x = 0
for i in range(101):
  x = i + x
print(x)

#Ejercicio 8 c
x = 0
z = 0
for i in range(0, 100, 2):
  x = i + x
  z += 1
print(x)
print(z)

#Ejercicio 8 d

x = 0
z = 0
for i in range(1, 100, 2):
  x = i + x
  z += 1
print(x)
print(z)

#Ejercicio 9

#Es un bucle infinito ya que no hay nada que cambie la condicion. Por lo tanto siempre dara True e imprimira siempre
0

#Ejercicio 10

def ingresarNumeros():
  numeros = []
  num = input("Ingrese un número para empezar: ")
  while num != "*":
      numeros.append(num)
      num = input("Ingrese otro numero, (* para salir) ")
  return numeros

numeros = ingresarNumeros()
umbral = int(input("Ingrese un valor umbral: "))

suma = 0
contador = 0
for num in numeros:
  suma = int(num) + suma
  contador += 1
  if (suma >= umbral):
    break

print("La secuencia de numeros es ", numeros)
print("El umbral es de ", umbral)
print("La suma de los primeros ", contador, "es de ", suma)

#Ejercicio 11

def ingresarNumeros():
  numeros = []
  while True:
    num = input("Ingrese numero, (* para salir) ")
    if num == "*":
      break
    numeros.append(num)
  return numeros

numeros = ingresarNumeros()

suma = 0
i = 0
while i < len(numeros):
  numero = int(numeros[i])
  i += 1
  if numero % 2 != 0:
    continue
  suma = suma + numero
print(numeros)
print(suma)

#Ejercicio 12
def sumaNaturales(num: int)->int:
  suma = 0
  for i in range(num):
    suma = i + suma
  return suma

while True:
  num = input("Ingrese un numero entero o 'salir' para terminar ")
  if num == "salir":
    break
  x = sumaNaturales(int(num))
  print(x)

#Ejercicio 13

billete_grosor = 0.11 * 0.001 # grosor de un billete en metros
altura_monumento = 70 # altura en metros
billetes_n = 1
dia = 1

altura = 0
while altura < 70:
  altura = 0.11 * 0.001 * billetes_n
  dia += 1
  billetes_n += 1

print("Pasaron ", dia, "dias para superar la altura")

#Ejercicio 14 a

num1 = int(input("Ingrese numero 1 "))
num2 = int(input("Ingrese numero 2 "))

contador = 0

for i in range(num1, num2):
  if i % num1 == 0:
    contador += 1
print(contador)

#Ejercicio 14 b

num1 = int(input("Ingrese numero 1 "))
num2 = int(input("Ingrese numero 2 "))

j = num1
i = 4
while j < num2:
  j = num1 * i
  i = i + 1

print(i)

#Ejercicio 14 b

num1 = int(input("Ingrese numero 1 "))
num2 = int(input("Ingrese numero 2 "))

j = num1
i = 0
while j < num2:
  j += num1
  i += 1

print(i)